config/routes.rb
require 'sidekiq/web'
C4c::Application.routes.draw do

  mount RailsAdmin::Engine => '//rails_admin', as: 'rails_admin'
  resources :charges do
    collection do
      get 'payment_failed'
    end
  end

  get '/feeds/validate_feed' => 'feeds#validate_feed', as: :validate_feed

  get '/tweets/fetch' => 'tweets#fetch'
  get '/search_tweets/:id' => 'feed_entries#search_tweets',:as=>"search_tweets"

  get '/auth/twitter', :as => :twitter_auth

  get "/mark_non_relavant"=> "tweets#mark_non_relavant",:as=>:mark_non_relavant
  get "/follow_conversation"=> "tweets#follow_conversation",:as=>:follow_conversation
  get "/unfollow_conversation"=> "tweets#unfollow_conversation",:as=>:unfollow_conversation
  get "/tweet_it"=> "tweets#tweet_it",:as=>:tweet_it
  get "/old_landing"=> "home#old_landing"
  get "/about_us"=> "home#about_us"
  get "/toc"=> "home#toc"
  get "/privacy-policy"=> "home#privacy_policy"
  get "/new_landing"=> "home#new_landing"

  resources :feed_entries do
    collection do
      get '/search' => 'feed_entries#search_blog_posts', :as => :search_blog_posts
      get '/fetch_new_articles' => 'feed_entries#fetch_new_articles', :as => :fetch_new_articles
      get '/fetch_tweets_and_email'=>'feed_entries#fetch_tweets_and_email',:as=>:fetch_tweets_and_email

    end
    member do
      get 'show_feed_tweets'
      get 'load_more_tweets'
      get 'load_more_tweets_for_keyword'
      get 'conversation_tweets'
      get 'following'
      get 'user_conversations'
      get 'remove_search_keyword'
      get 'add_search_keyword'
      get 'toggle_blog_important'
      get 'render_tweets'
      get 'render_fetch_tweet'
      get "update_last_seen"

    end
  end

  devise_for :users

  resources :feeds
  post '/feeds/import' => "feeds#import", :as => :feed_import
  get '/guest/sign_in' => "users#social_sign_in", :as => :social_sign_in

  get '/auth/:provider/callback' => "users#social_sign_in"

  post '/users/update_email' => "users#update_email", :as => :update_email
  post '/home/signup' => 'home#signup', as: :signup_import

  get '/feeds/deactivate/:id' => 'feeds#deactivate', as: :feed_deactivate
  get '/feeds/activate/:id' => 'feeds#activate', as: :feed_activate

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == 'admin' && password == 'admin123'
  end
  mount Sidekiq::Web => '/sidekiq_workers'

root 'home#index'

end

app/models/feed_entry.rb
class FeedEntry
  include Mongoid::Document
  include Mongoid::Timestamps
  include TfIdf

  paginates_per 100

  field :title
  field :url
  field :bitly_url
  field :author
  field :summary
  field :content
  field :important, type: Boolean
  field :published, type: Time
  field :categories, type: Array
  field :keywords, type: Array
  field :load_more_count,type: Integer,:default=>0
  field :load_more,type: Boolean,:default=>false
  field :is_searching,type: Boolean,:default=>false
  field :last_seen_at,type: DateTime
  has_and_belongs_to_many :search_keywords

  belongs_to :feed
  belongs_to :user

  validates_presence_of :user_id
  validates_presence_of :feed_id
  has_many :user_conversations,:dependent=>:destroy
  after_create :add_bitly_url

  def add_bitly_url
    self.bitly_url = BitlyUrl.new(self.url.to_s).short_url rescue nil  
    self.save
  end

  def generate_keywords(feed)
    tf_idf = TfIdf::TfIdfScore.new(self.content, feed.feed_entries.map{|fe| fe.content})
    self.keywords = tf_idf.get_score.sort_by{|k, v| v}.first(5).map{|a| a[0]}
    self.save
  end

  def search_by_keywords(keywords)
    search_keyword_tweets= []
    (keywords).split(",").flatten.compact.uniq.each do |keyword|
      if keyword.present?
        search_keyword =SearchKeyword.where(:keyword=>keyword.downcase).first
        search_keyword =SearchKeyword.create(:keyword=>keyword.downcase) if search_keyword.blank?
        self.search_keywords = [self.search_keywords,search_keyword].flatten.compact.uniq
        # start_searching
        self.save 
        #  Return keyword search time
        
        search_keyword_tweets.push << TweetSearchWorker.perform_async(search_keyword.id.to_s,self.id.to_s)
      end  
    end
    # search_keyword_tweets.flatten.compact.uniq
  end

  def remove_search_keyword(keyword)
    search_keyword_ids.delete(keyword.id)
    self.save
  end

  def tweets
    search_keywords.collect{|x|x.tweets.parent_tweets.has_children}
  end

  def relavant_tweets

    search_keywords.collect { |keyword| keyword.tweets.parent_tweets.has_children.relavant_tweets.includes(:replies).to_a }.flatten.compact.uniq
    
    # search_keywords.collect { |keyword| keyword.tweets.parent_tweets.relavant_tweets.to_a }.flatten.compact.uniq
    
  end

  def add_search_keyword(keyword)
    search_keyword = SearchKeyword.where(:keyword=>keyword.downcase).last
    search_keyword = SearchKeyword.create(:keyword=>keyword.downcase) if search_keyword.blank?
    self.search_keywords = [self.search_keywords,search_keyword].flatten.compact.uniq
    # start_searching
    self.save
    TweetSearchWorker.perform_async(search_keyword.id.to_s,self.id.to_s)
    search_keyword
  end

  def people_talking_count
    all_replies = self.tweets.flatten.collect { |t| t.replies.count }
    all_replies.present? ? all_replies.inject { |people_talking, reply_count| people_talking + reply_count } : 1
  end

  def last_reply_time
    all_replies = self.tweets.flatten.collect { |t| t.replies}
    all_replies.present? ?  all_replies.last.last.tweet_data['tweet']['created_at'] : nil
  end

  def clicks_count
    client = Bitly.client
    client.clicks(self.bitly_url).user_clicks
  rescue
    0
  end

  def start_load_more
    self.load_more = true
    self.load_more_count = 0
    self.save
  end

  def update_load_more_count
    self.load_more_count = self.load_more_count + 1
    if self.load_more_count == self.search_keywords.size
      self.load_more = false
      self.load_more_count = 0
      self.save
    end
  end
  
  def start_searching
    self.is_searching = true
    self.save
  end

  def update_searching
    self.is_searching = false
    self.save
  end

  def update_last_seen
    self.last_seen_at = DateTime.now
    self.save
  end

  def unseen_tweets
    search_keywords.collect { |keyword| keyword.tweets.parent_tweets.has_children.relavant_tweets.unseen_tweets(self.last_seen_at)}.flatten.compact.uniq
  end

end

app/models/keyword.rb
class Keyword
  include Mongoid::Document

  field :keyword, type: String
  has_and_belongs_to_many :tweets
end

app/controllers/feed_entries_controller.rb
class FeedEntriesController < ApplicationController

  before_filter :add_email_id,:except=>[:index]
  before_filter :user_is_authenticated!
  before_filter :get_feed, only: [:index, :search_blog_posts, :fetch_new_articles]
  before_filter :check_stripe_info
  
  def index
    if !@feed.nil?
      order = [[:important, :desc], [:published, :desc]]
      @feed_entries = []
      case params[:filter]
      when 'oldest'
        order = [[:published, :asc]]
        @feed_entries = @feed.feed_entries.order_by(order).page params[:page]
      when 'important'
        order = [[:important, :desc], [:published, :desc]]
        @feed_entries = @feed.feed_entries.order_by(order).page params[:page]
      when 'conversations'
        order = [['feed_entry.user_conversations.count', :desc], [:published, :desc]]
        list = @feed.feed_entries.includes(:user_conversations).sort_by{ |entry| entry.user_conversations.count}
        @feed_entries = Kaminari.paginate_array(list.reverse).page params[:page]
      else
        order = [[:published, :desc]]
        @feed_entries = @feed.feed_entries.order_by(order).page params[:page]
      end 
    end
  end

  def show
    @feed_entry = FeedEntry.find(params[:id])
    @tweets =  @feed_entry.relavant_tweets
    @user_converations = current_user.get_feed_entry_conversation(@feed_entry.id)
    
  end

  def new
    @feed_entry = FeedEntry.new
  end

  def edit
  end

  def create
    @feed_entry = FeedEntry.new(feed_entry_params)

    if @feed_entry.save
      redirect_to @feed_entry, notice: 'Feed entry was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @feed_entry.update(feed_entry_params)
      redirect_to @feed_entry, notice: 'Feed entry was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @feed_entry.destroy
    redirect_to feed_entries_url, notice: 'Feed entry was successfully destroyed.'
  end

  # temporary action for followed conversations
  def following
    @feed_entry = FeedEntry.find(params[:id])
    @user_converations = current_user.get_feed_entry_conversation(@feed_entry.id)
  end

  def search_tweets
    @feed_entry = FeedEntry.find(params[:id])

     @feed_entry.search_by_keywords(params[:keywords])
     # @feed_entry.start_searching
     
    # Considering one kwey word
    
    @search_keyword =  SearchKeyword.where(:keyword=>params[:keywords].downcase.strip).first
     
    #  If existing key word is added
    if @search_keyword && @search_keyword.tweets.parent_tweets.has_children.relavant_tweets.present?
      @tweets =  @search_keyword.tweets.parent_tweets.has_children.relavant_tweets
      render "search_tweets"
    else
      render :json=>{:success=>true}
    end
  end

  def load_more_tweets
    @feed_entry = FeedEntry.find(params[:id])
    @tweets = @feed_entry.search_by_keywords(@feed_entry.search_keywords.pluck(:keyword).join(","))
    @feed_entry.start_load_more
    render :json=>{:success=>true}
    #render "search_tweets"
  end

  def load_more_tweets_for_keyword
    if params[:keyword_id]
      @feed_entry = FeedEntry.find(params[:id])
      @search_keyword = SearchKeyword.find(params[:keyword_id])
      @tweets = @feed_entry.search_by_keywords(@search_keyword.keyword)
    end  

    render :json=>{:success=>true}
    # render "search_tweets"
  end

  def show_feed_tweets
    @feed_entry = FeedEntry.find(params[:id])
    @tweets =  @feed_entry.relavant_tweets
    render "search_tweets"
  end

  def conversation_tweets
    @feed_entry = FeedEntry.find(params[:id])
    @conversation_tweets = current_user.user_conversations.where(:feed_entry_id=>@feed_entry.id).collect{|x|x.tweet}.flatten.compact.uniq
    
    if @conversation_tweets.present?
      render :json=>{:tweets=>@conversation_tweets,:tweet_ids=>@conversation_tweets.collect{|x| x.id}}
    else
      render :json=>{:tweets=>[],:tweet_ids=>[]}
    end
  end

  def user_conversations
    @feed_entry = FeedEntry.find(params[:id])
    @user_conversations = current_user.get_feed_entry_conversation(@feed_entry.id)
  
  end

  def remove_search_keyword
    @feed_entry = FeedEntry.find(params[:id])
    @search_keyword = @feed_entry.search_keywords.find(params[:keyword_id])
    if @feed_entry.remove_search_keyword(@search_keyword) && @search_keyword.remove_feed_entry(@feed_entry)
      render :json=>{:success=>true}
    else
      render :json=>{:success=>false}
    end
  end

  def add_search_keyword
    @feed_entry = FeedEntry.find(params[:id])
    @keyword = @feed_entry.add_search_keyword(params[:keywords])
  end

  def search_blog_posts
    @feed_entries = @feed.feed_entries.where(:title => /.*#{params[:search]}.*/i) if !@feed.nil?
  rescue
    @feed_entries = nil
  end

  def fetch_new_articles
    @feed_entries = @feed.add_feed_entries
  end

  def toggle_blog_important
    @feed_entry = FeedEntry.find(params[:id])
    @feed_entry.important = !@feed_entry.important
    if @feed_entry.save
      render :json=>{:success=>true}
    else
      render :json=>{:success=>false}
    end
  end

  def render_tweets
    
    @feed_entry = FeedEntry.find(params[:id])
    @tweets = Tweet.where(:id.in=>params[:tweet_ids])
    @search_keyword = SearchKeyword.find(params[:search_keyword_id])
    render "search_tweets"
  end
  # Single tweet
  def render_fetch_tweet
    @feed_entry = FeedEntry.find(params[:id])
    
    @tweets = Tweet.where(:id.in=>params[:tweet_ids])
    
    
    render "search_tweets"
  end
  def update_last_seen
    @feed_entry = FeedEntry.find(params[:id])
    @feed_entry.update_last_seen
    render :json=>{:success=>true}
  end

  def fetch_tweets_and_email
    ScheduleTweetSearchWorker.perform_async
    redirect_to root_url
  end
  private
  def get_feed
    feeds = Feed.where(:user_id => current_user.id, :active => true)
    @feed = feeds.first
  end
end

app/helpers/feed_entries_helper.rb
module FeedEntriesHelper
  def entries
    !@feed_entries.nil? ? @feed_entries : []
  end

  def feed_entry_keywords
    return [] if @feed_entry.keywords.nil?
    @feed_entry.keywords
  end

  def screen_name(t)
    t.user.screen_name.to_s rescue ''
  end

  def tweet_text(t)
    t.text rescue ''
  end

  def posted_on(t)
    '10 days ago'
  end

  def hash_tag(t)
    "ruby"
  end
end

app/views/feed_entries/_blog_list.html.erb
<% if !@feed_entries.nil? %>
<div id='left-side'>
  <% (0..(@feed_entries.length - 1)).step(2).each_with_index do |i, index| %>
  <% break if @feed_entries[i].nil?  %>
  <%= render :partial => 'single_blog', :locals => {:feed => @feed_entries[i], :post_id => ('lhs' + index.to_s)} %>
  <%end%>
</div>
<div id='right-side'>
  <% (0..(@feed_entries.length - 1)).step(2).each_with_index do |i, index| %>
      <% break if @feed_entries[i+1].nil?  %>
      <%= render :partial => 'single_blog', :locals => {:feed => @feed_entries[i+1], :post_id => ('rhs' + index.to_s)} %>
  <% end %>
</div>
<% end %>

app/views/feed_entries/_feed_entries_header.html.erb
<div id="header-below" class='row'>
  <div class="heder-next-left span8">
    <h1 class="story-title">
      <!-- <a href=".url.to_s"> -->
      <%= link_to @feed_entry.title, @feed_entry.url.to_s, :target => 'blank' %>
    </h1>
    <div class="post-stats small-txt"> 
      <div><%= @feed_entry.clicks_count rescue '0' %></div>people viewed your post via 
      <a href="http://twitter.com/c4chq" target="_blank">@C4C</a>
    </div>
  </div>
    <!-- <i class="separator-dash">
      <%= '' %>
    </i> -->
  <div class="follow-section span2 <%= 'active' if active_class=='following'%>">
    <%= link_to "#{@user_converations.size} Following", following_feed_entry_path(@feed_entry) %>
    <div class="link-description">
     Conversations you are following
    </div>
  </div>
  <div class="feed-section span2 <%= 'active' if active_class=='feed'%>">
    <%= link_to 'Feed', feed_entry_path(@feed_entry) %>
    <div class="link-description">
      Search Live Conversation
    </div>
  </div>
</div>

app/views/feed_entries/_feed_entries_tags_search.html.erb
<div class="input-section clearfix">
  <div class="search-terms">
    <div class="search-terms-head">Twitter Search terms</div>
    <div class="search-terms-note small-txt">Add in the keywords with comma to search twitter conversations around this topic</div>
  </div>
  <%= form_tag(search_tweets_path(@feed_entry),:method=>:get,:id=>"keyword_search_form", :class=>"clearfix") do%>
  <%= text_field_tag :keywords,params[:keywords],:placeholder=>"Example: Keyword One, #Hashtag, @TwitterName",:type=>"search",:class=>"input-tags" %>
  <button class="search-keyword round-corner">
    Add Keyword
  </button>
  <% end %>
</div>
<div class="tags small-txt">
  <ul class="keywords">
    <% @feed_entry.search_keywords.each do |keyword| %>
    <li class="round-corner">
      <span class="searchTag">   <%="#{keyword.keyword} (#{keyword.tweets.parent_tweets.has_children.size})" %></span>
   
      <%= link_to "<i class='loading'></i>".html_safe, remove_search_keyword_feed_entry_path(@feed_entry,:keyword_id=>keyword.id) ,:class=>"remove_search_keyword" ,"data-keyword-id"=>keyword.id ,"data-search-name"=>keyword.keyword%>
    </li>
    <% end %>
  </ul>
</div>

app/views/feed_entries/_feed_tweet_template.html.erb
<script id="tweet_template" type="text/x-handlebars-template">
  <div class="post-area round-corner feed-tweets" id="tweet_{{tweet_id.$oid}}" data-feed-entry-id="{{feed_entry_id}}" data-keyword-id="{{searchKeywordIds search_keywords}}">
    <div class="post-area-heading clearfix">
    
    
      {{#isFollowConversation tweet_id}}
        <div class="fontawesome-unfollow"  data-id={{tweet_id.$oid}} data-feed-entry-id="{{feed_entry_id}}" id="follow_{{tweet_id.$oid}}">Unfollow conversation</div>
      {{else}}
        <div class="fontawesome-follow" data-id={{tweet_id.$oid}} data-feed-entry-id="{{feed_entry_id}}" id="follow_{{tweet_id.$oid}}">Follow conversation</div>
      {{/isFollowConversation}}
     <div class="fontawesome-map-marker">{{displayTweetLocation tweet_data  }}</div> 
    <div class="relevance" data-id={{tweet_id.$oid}}>Mark Not Relevant</div>
    </div>

    <div class="post-tags small-txt">
        {{#each search_keywords}}
          <span class="round-corner" data-search-name="{{this.keyword}}" data-search-keyword-id={{this.$oid}}>{{this.keyword}}</span>
        {{/each}}
        {{#if is_unseen }}
          <span class="new-tweet">New</span>
        {{/if}}
    </div>
    <div id="activity">
      by <a href={{tweet_data.actor.link}} class="by-user" target="_blank">{{screenName tweet_data.actor.link}} </a>
        <span class="by-user-time">
            {{showTweetTime tweet_data.object.postedTime}}
        </span>
    </div>
    <div class="post-section clearfix">
      <p class="post-text">
        {{ tweet_data.body }}
      </p>
      
      {{#isUrls tweet_data.content.twitter_entities }}
        <p>
          {{#each tweet_data.content.twitter_entities.urls}}
            <a href={{this.expanded_url}} class="post-link">{{this.expanded_url}} </a>
          {{/each}}
        </p>  
        {{/isUrls}}

      <a href="#" class="fontawesome-reply round-corner" data-id={{tweet_id.$oid}} data-screen-name="@{{screenName tweet_data.actor.link}}">Reply</a>
      <div class="replyBox"></div>
      <div id="tweet_message_{{tweet.tweet_id.$oid}}" class="reply_tweet_mesage"></div>
    </div>

    <div class="post-tweets small-txt">

      {{#each replies}}
        {{> tweet_reply}}
      {{/each}}  
      
  </div>
</script>

app/views/feed_entries/_form.html.erb
<%= form_for @feed_entry do |f| %>
  <% if @feed_entry.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@feed_entry.errors.count, "error")} prohibited this feed_entry from being saved:" %>
      </h2>
      <ul>
        <% @feed_entry.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/feed_entries/_import_feed.html.erb
<div class="empty-feed">
  <div class="import-feed-now">To get started, import a blog feed</div>
    <%= form_tag(feeds_path,:id=>"import_feed_form") do %>
      <%= text_field_tag :url,'', class: 'import-feed-input', placeholder: 'http://Enter Blog URL' %>
      <button type="submit" name="Import now" value="submit" class="submit-now">
        Import Blog
      </button>
    <% end %>
  </div>
</div>
<%= content_for :javascript do %>
  <script type="text/javascript">
    C4C.verifyFeed.initImportFeed();
  </script>
<% end %>

app/views/feed_entries/_mark_non_relavant_template.html.erb
<script id="mark_non_relavant_template" type="text/x-handlebars-template">
<div class="undo-conv" data-id={{id}} id="non_relavant_{{id}}">
  <div class="unrelevant" >Permanently remove this conversation ?</div>
  <button class="remove-tweet round-corner" id="unrelevant_{{id}}">Remove</button>
  <button class="undo round-corner" id="undo_{{id}}">Cancel</button>
</div>  
</script>

app/views/feed_entries/edit.html.erb
<h1>Editing feed_entry</h1>
<%= render 'form' %>
<%= link_to 'Show', @feed_entry %>
\|
<%= link_to 'Back', feed_entries_path %>

app/views/feed_entries/index.html.erb
<% if current_user.email.blank? %>
<%= render partial: '/feed_entries/modal_form' %>
<% end %>
<% if @feed_entries.nil? || @feed_entries.empty? %>
<%= render partial: 'import_feed' %>
<% else %>
<div class="search clearfix" id="timeline-section-with-search">
  <div class="feed-title clearfix">
    <a href="/feed_entries/" title="Your imported blog">
      <h1 class="blog-name">
        <%= @feed.title %>
      </h1>
    </a>
    <div class="new-posts-status alert"><%= flash[:message]%></div>
    <a href="<%=fetch_new_articles_feed_entries_path%>" class="fetch-new-posts h1 c4c-tooltip" data-remote='true' data-c4ctooltip='Fetch New Posts'>
      <i class='fontawesome-refresh'></i>
    </a>
  </div>
  <div class="search-side clearfix">
    <div class="sort">
      <span>Sort by</span>
      <select id='sort-selector' class="round-corner">
        <option value="<%=feed_entries_path%>" <%unless params[:filter].present?%>selected<%end%>>Latest First</option>
        <option value="<%=feed_entries_path(:filter => 'oldest')%>" <%if params[:filter]=='oldest'%>selected<%end%>>Oldest First</option>
        <option value="<%=feed_entries_path(:filter => 'conversations')%>" <%if params[:filter]=='conversations'%>selected<%end%>>Most Conversations</option>
        <option value="<%=feed_entries_path(:filter => 'important')%>" <%if params[:filter]=='important'%>selected<%end%>>Important First</option>

        <!--
        <ul class='dropdown'>
        <li><a href="<%=feed_entries_path%>" <%unless params[:filter].present?%>class='active'<%end%>>Latest First</a></li>
        <li><a href="<%=feed_entries_path(:filter => 'oldest')%>" <%if params[:filter]=='oldest'%>class='active'<%end%>>Oldest First</a></li>
        <li><a href="<%=feed_entries_path(:filter => 'conversations')%>" <%if params[:filter]=='conversations'%>class='active'<%end%>>Most Conversations</a></li>
        <li><a href="<%=feed_entries_path(:filter => 'important')%>" <%if params[:filter]=='important'%>class="active"<%end%>>Important First</a></li>
        </ul>
      -->
    </select>
  </div>
  <span class="loading"  style="display: none;"></span>
  <div class="search-field">
    <input class="round-corner" placeholder="Search Blog Title..." type="search" id='search_blog_input' data-url="<%=search_blog_posts_feed_entries_path%>" />
  </div>



</div>
</div>
<div id="blog-list" class="clearfix">
  <%= render partial: 'blog_list' %>
</div>

<div class="load-more">
  <%= link_to_next_page @feed_entries, 'Load more Blog Posts', :id=>'load_more_link', :params=>params%>
</div>
<script>

  $(document).ready( function() {
    C4C.feedEntries.loadMoreBlogPosts();
    C4C.feedEntries.searchBlogPosts();
    $('.fetch-new-posts').bind('ajax:beforeSend', function(){
      $('.fetch-new-posts').addClass( 'rotate-continuous' );
    });
    $('.fetch-new-posts').bind('ajax:complete', function(){
      $('.fetch-new-posts').removeClass( 'rotate-continuous' );
      $('.new-posts-status').fadeIn().delay(2000).fadeOut();
    });

    $( '[data-c4ctooltip]' ).c4cTooltip();  // Init tooltips.



    var sort_select = document.getElementById('sort-selector');
    sort_select.onchange = function(){
      console.log('changed');
      window.location = this.value;
    };



  });
</script>

<% end %>

app/views/feed_entries/new.html.erb
<h1>New feed_entry</h1>
<%= render 'form' %>
<%= link_to 'Back', feed_entries_path %>

app/views/feed_entries/show.html.erb
<%= render partial: 'feed_entries_header' ,:locals=>{:active_class=>"feed"}%>
<div class="tags-search-outer row">
  <div id="tags-search">
    <%= render partial: 'feed_entries_tags_search' %>
  </div>
</div>
<!-- <div class="clearfix js-masonry" id="content-area" 
  data-masonry-options='{ "columnWidth": "48%", "itemSelector": ".post-area" }'> -->
  <div class="clearfix" id="content-area" ></div>
<div class="zero-keywords">
  <h3>NO KEYWORD ADDED:</h3>
  Setup your blog.
  Empower your blog to reach out to people who are talking on this topic. Go ahead and add the search terms.
</div>
<div class="load-more">
  <% if @feed_entry.load_more %>
    We're working on finding more conversations. We'll notify you once we are done
  <% else %>
    <a href="<%= load_more_tweets_feed_entry_path(@feed_entry) %>" title="Load More Conversations" id="load_more_tweets">Load more conversations</a>
  <% end %>  

  <span id="load_more_search_message" style="display:none;">We're working on finding more conversations. We'll notify you once we are done</span>
</div>
<%= render :partial=>"reply_text_template" %>
<%= render :partial=> "feed_tweet_template" %>

<%= render :partial=>"mark_non_relavant_template" %>
<%= render :partial=>"reply_tweet_template" %>
<%= render :partial=>"search_keyword_tag_template" %>
<%= subscribe_to "/tweets/#{@feed_entry.id.to_s}" %>
<%= content_for :javascript do %>
<script>

  $(document).ready( function() {
    if ($('.searchTag').html()) {
      if ($('.searchTag').html().length > 0){
        $('.zero-keywords').hide();
      }
    }
    C4C.twitterFeed.setConversationTweets("<%= conversation_tweets_feed_entry_path(@feed_entry)%>",true)
    // C4C.twitterFeed.showFeedTweets("<%= show_feed_tweets_feed_entry_path(@feed_entry)%>")
    C4C.twitterFeed.setFeedEntryID("<%= @feed_entry.id%>");
    <% tweet_ids = @tweets.collect{|tweet|tweet.id.to_s}.to_a %>
    C4C.twitterFeed.renderExistingTweets(<%=raw tweet_ids%>)
    
    C4C.twitterFeed.searchTweet();
    C4C.twitterFeed.loadMoreTweets();
    C4C.twitterFeed.removeSearchKeyword();
    C4C.twitterFeed.setFeedUrl("<%= @feed_entry.bitly_url%>");
    
    C4C.c4cTemplate.initSearchKeywordTagTemplate();
    C4C.twitterFeed.toggleImportantFlag();
    C4C.twitterFeed.subscribePrivatePub();
    C4C.twitterFeed.highlightConversation()
    
  // $(".heder-next-right > div > a").click(function(){
  // $(this).parent("div").addClass("active").siblings("div").removeClass("active");
  // $(this).parent('div').addClass('active');
  // $(this).parent('div').sibing('div').removeClass('active');
// });

  // remove the tags on clicking the cross
  // $('.tags > ul > li >.fontawesome-remove').click(function() {
  //   $(this).parent('li').remove();
  // });
});
</script>

<% end %>