config/routes.rb
require 'sidekiq/web'
C4c::Application.routes.draw do

  mount RailsAdmin::Engine => '//rails_admin', as: 'rails_admin'
  resources :charges do
    collection do
      get 'payment_failed'
    end
  end

  get '/feeds/validate_feed' => 'feeds#validate_feed', as: :validate_feed

  get '/tweets/fetch' => 'tweets#fetch'
  get '/search_tweets/:id' => 'feed_entries#search_tweets',:as=>"search_tweets"

  get '/auth/twitter', :as => :twitter_auth

  get "/mark_non_relavant"=> "tweets#mark_non_relavant",:as=>:mark_non_relavant
  get "/follow_conversation"=> "tweets#follow_conversation",:as=>:follow_conversation
  get "/unfollow_conversation"=> "tweets#unfollow_conversation",:as=>:unfollow_conversation
  get "/tweet_it"=> "tweets#tweet_it",:as=>:tweet_it
  get "/old_landing"=> "home#old_landing"
  get "/about_us"=> "home#about_us"
  get "/toc"=> "home#toc"
  get "/privacy-policy"=> "home#privacy_policy"
  get "/new_landing"=> "home#new_landing"

  resources :feed_entries do
    collection do
      get '/search' => 'feed_entries#search_blog_posts', :as => :search_blog_posts
      get '/fetch_new_articles' => 'feed_entries#fetch_new_articles', :as => :fetch_new_articles
      get '/fetch_tweets_and_email'=>'feed_entries#fetch_tweets_and_email',:as=>:fetch_tweets_and_email

    end
    member do
      get 'show_feed_tweets'
      get 'load_more_tweets'
      get 'load_more_tweets_for_keyword'
      get 'conversation_tweets'
      get 'following'
      get 'user_conversations'
      get 'remove_search_keyword'
      get 'add_search_keyword'
      get 'toggle_blog_important'
      get 'render_tweets'
      get 'render_fetch_tweet'
      get "update_last_seen"

    end
  end

  devise_for :users

  resources :feeds
  post '/feeds/import' => "feeds#import", :as => :feed_import
  get '/guest/sign_in' => "users#social_sign_in", :as => :social_sign_in

  get '/auth/:provider/callback' => "users#social_sign_in"

  post '/users/update_email' => "users#update_email", :as => :update_email
  post '/home/signup' => 'home#signup', as: :signup_import

  get '/feeds/deactivate/:id' => 'feeds#deactivate', as: :feed_deactivate
  get '/feeds/activate/:id' => 'feeds#activate', as: :feed_activate

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == 'admin' && password == 'admin123'
  end
  mount Sidekiq::Web => '/sidekiq_workers'

root 'home#index'

end

app/models/feed.rb
class Feed
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :url, type: String
  field :bitly_url, type: String
  field :active, type: Boolean

  has_many :feed_entries,:dependent=>:destroy
  belongs_to :user

  validates_presence_of :user_id
  validates_presence_of :url
  validates_presence_of :active

  def import(params)

    if FeedParser.valid?(params[:url])
      parsed_feed = FeedParser.new(params[:url])
      save_(parsed_feed, params[:user_id])
    else
      nil
    end  
  end

  # def add_feed_entry(feed_entry, user_id)
  #   self.feed_entries.create!(feed_entry_hash(e, user_id))
  # end
  def add_feed_entries
    feed_entry_blogs = self.feed_entries.pluck(:title)
    new_feeds = []
    parsed_feed = FeedParser.new(self.url)
    new_entries = parsed_feed.entries.select{|x|!feed_entry_blogs.include?(x.title.to_s)}
    new_entries.each do |feed_entry|
        new_feeds << self.feed_entries.create!(feed_entry_hash(feed_entry, self.user_id))
    end
    new_feeds
  rescue => e
    Rails.logger.error e  
    return []
  end

  private
  def save_(feed, user_id = nil)
    self.title = feed.title.to_s rescue nil
    self.url = feed.url.to_s
    self.bitly_url = BitlyUrl.new(feed.url.to_s).short_url rescue nil
    self.user_id = user_id.to_s
    self.active = true

    if self.save
      feed.entries.each do |e|
        self.feed_entries.create!(feed_entry_hash(e, user_id))
      end
      self
    else
      logger.info(" ====ERROR==== ")
      logger.info(self.errors.full_messages)
      return nil
    end
  rescue Exception => e
    logger.info(e.message)
    logger.info(e.backtrace)
    nil
  end

  def feed_entry_hash(e, user_id)
    {
      :title => (e.title.to_s rescue nil),
      :url => (e.url.to_s rescue nil),
      :author => (e.author.to_s rescue nil),
      :summary => (e.summary.to_s rescue nil),
      :content => (e.content.to_s rescue nil),
      :published => (e.published rescue nil),
      :categories => (e.categories rescue []),
      :user_id => user_id
    }
  end

 
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  

  # GET /feeds
  def index
    @feeds = Feed.where(:user_id => current_user.id)
  end

  # GET /feeds/1
  def show
    # @feed = Feed.where(:active => true)
    # @feed_entries = @feed.feed_entries
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  def create
    params[:feed][:user_id] = current_user.id
    @feed = current_user.feeds.new.import(params[:feed])
    if @feed.present?
      redirect_to feed_entries_path, notice: 'Feed was successfully created.'
    else  
      redirect_to feed_entries_path

    end
  end

  # PATCH/PUT /feeds/1
  def update
    if @feed.update(feed_params)
      redirect_to @feed, notice: 'Feed was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /feeds/1
  def destroy
    @feed.destroy
    redirect_to feeds_url, notice: 'Feed was successfully destroyed.'
  end

  def deactivate
    Feed.find(params[:id]).update_attribute(:active, false)
    redirect_to feeds_path
  end
  def activate
    Feed.find(params[:id]).update_attribute(:active, true)
    redirect_to feeds_path
  end

  def validate_feed

    respond_to do |format|
      format.json{
        render json: FeedParser.valid?(params['url'].strip)
      }
    end
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for @feed do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@feed.errors.count, "error")} prohibited this feed from being saved:" %>
      </h2>
      <ul>
        <% @feed.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="fields">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>
<%= render 'form' %>
<%= link_to 'Show', @feed %>
\|
<%= link_to 'Back', feeds_path %>

app/views/feeds/import.html.erb
<%= form_tag url_for(feed_import_path) do %>
  <%= label_tag :url %>
  <%= text_field_tag :url %>
  <%= submit_tag 'Import feed' %>
<% end %>

app/views/feeds/index.html.erb
<style type="text/css">
table, th, td
{
border: 1px solid black;
padding: 10px;
}
</style>
<div style="margin:20px">
<% if @feeds.length > 1 %>
  <%= "Please activate only one of the following feeds: " %>
  <table border="2">
    <thead>
      <tr>
        <th>Feed</th>
        <th>Status</th>
        <th>Manage</th>
      </tr>
    </thead>  
    <tbody>
      <% @feeds.to_a.each do |feed| %>
        <tr>
          <td><%= feed.title.to_s %></td>
          <td><%= feed.active? ? "Active" : "In active" %></td>
          <td>
            <% if feed.active? %>
              <%= link_to 'Deactivate', feed_deactivate_path(feed) %>
            <% else %>  
              <%= link_to 'Activate', feed_activate_path(feed) %>
            <% end %>
          </td>
        </tr>  
      <% end %>
    </tbody>  
  </table>  
<% end %>
</div>
<% if @feeds.length == 1 %>
  <%= link_to @feeds.first.title.to_s, feed_entries_path %>
<% end %>

app/views/feeds/new.html.erb
<h1>New feed</h1>
<%= render 'form' %>
<%= link_to 'Back', feeds_path %>