config/routes.rb
require 'sidekiq/web'
C4c::Application.routes.draw do

  mount RailsAdmin::Engine => '//rails_admin', as: 'rails_admin'
  resources :charges do
    collection do
      get 'payment_failed'
    end
  end

  get '/feeds/validate_feed' => 'feeds#validate_feed', as: :validate_feed

  get '/tweets/fetch' => 'tweets#fetch'
  get '/search_tweets/:id' => 'feed_entries#search_tweets',:as=>"search_tweets"

  get '/auth/twitter', :as => :twitter_auth

  get "/mark_non_relavant"=> "tweets#mark_non_relavant",:as=>:mark_non_relavant
  get "/follow_conversation"=> "tweets#follow_conversation",:as=>:follow_conversation
  get "/unfollow_conversation"=> "tweets#unfollow_conversation",:as=>:unfollow_conversation
  get "/tweet_it"=> "tweets#tweet_it",:as=>:tweet_it
  get "/old_landing"=> "home#old_landing"
  get "/about_us"=> "home#about_us"
  get "/toc"=> "home#toc"
  get "/privacy-policy"=> "home#privacy_policy"
  get "/new_landing"=> "home#new_landing"

  resources :feed_entries do
    collection do
      get '/search' => 'feed_entries#search_blog_posts', :as => :search_blog_posts
      get '/fetch_new_articles' => 'feed_entries#fetch_new_articles', :as => :fetch_new_articles
      get '/fetch_tweets_and_email'=>'feed_entries#fetch_tweets_and_email',:as=>:fetch_tweets_and_email

    end
    member do
      get 'show_feed_tweets'
      get 'load_more_tweets'
      get 'load_more_tweets_for_keyword'
      get 'conversation_tweets'
      get 'following'
      get 'user_conversations'
      get 'remove_search_keyword'
      get 'add_search_keyword'
      get 'toggle_blog_important'
      get 'render_tweets'
      get 'render_fetch_tweet'
      get "update_last_seen"

    end
  end

  devise_for :users

  resources :feeds
  post '/feeds/import' => "feeds#import", :as => :feed_import
  get '/guest/sign_in' => "users#social_sign_in", :as => :social_sign_in

  get '/auth/:provider/callback' => "users#social_sign_in"

  post '/users/update_email' => "users#update_email", :as => :update_email
  post '/home/signup' => 'home#signup', as: :signup_import

  get '/feeds/deactivate/:id' => 'feeds#deactivate', as: :feed_deactivate
  get '/feeds/activate/:id' => 'feeds#activate', as: :feed_activate

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == 'admin' && password == 'admin123'
  end
  mount Sidekiq::Web => '/sidekiq_workers'

root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  http_basic_authenticate_with name: "idyllic", password: "p@ssw0rd"

  before_filter :redirect_if_signed_in,:except=>[:about_us,:toc,:privacy_policy]
  def index
    @new_user = session[:new_user]
    render 'index', layout: false
  end

  def old_landing
    render layout: false
  end

  def new_landing
    render layout: false
  end

  def signup
    session[:blog_url] = params[:url] if !params[:url].empty?
    redirect_to twitter_auth_path, method: :get
  end

  def redirect_if_signed_in
    if user_signed_in?
      redirect_to feed_entries_path
    end
  end
end

app/views/home/_twitter_search.html.erb
<%= form_tag twitter_search_path do %>
  <%= label_tag :search %>
  <%= text_field_tag :search %>
  <%= submit_tag :search %>
<% end %>

app/views/home/about_us.html.erb
<div class="about-us-top span12">
  <div class="top-dash"></div>
  <h1>Our Story</h1>
  <span class="span6">
     <!-- <h3 class="head-text">Our Story</h3> -->

   <!--  <strong>Jinesh Parekh</strong> <br>
   <span class="disabled-link">Co-founder, Operations &amp; Engineering</span> -->
  <p class="">
     We started our journey on the belief that every single piece of authentic content, deserves attention from those who it was written for. You are not Seth Godin, but that does not mean your voice should not be heard. We want your content to reach out to people who are talking around it right now. 
  </p>   
  <br/>
  <p>
    We’re here to help people who write genuine content. Before we define what we mean by genuine content, let us describe what genuine content is not.
  </p>
  <br/>
  <p>Your content is not genuine if:
    <ol style="list-style-type:decimal;margin-left:20px;margin-top:10px">
      <li>The sole purpose of your content is to get high traffic on your website.</li>
      <li>The content is stuffed with keywords for SEO purposes</li>
      <li>The sole purpose of your content is to get high traffic on your website.</li>
    </ol>  
  </p>
  <br/>
  <p>
    We define genuine content as the one that was written for truly helping your audience on what they are looking for. This is the true essence of Inbound Marketing.
  </p>
  <br/>
  <h3>How did it started?</h3>
  <p>
    As part of Inbound marketing for our company Idyllic Software, we produced truly authentic content. However we quickly realized that our content was not reaching those whom it was written for. Hence we wished goodbye to our Inbound Marketing tool with this <a href="http://blog.idyllic-software.com/why-did-i-quit-on-hubspot/">final word</a> and embarked on the journey to build C4C.


  </p>
  </span>
</div>

<!-- <address class="pull-right">
  <strong>Idyllic Software</strong>
  <p>212 Clara st.</p>
  <p>San Fransisco, CA 912121</p>
  <a href="mailto:feedback@c4chq.com">Contact Us</a>
</address>

<div class="about-us-desc">

  <h3 class="head-text">Our Story</h3>

  <p class="">
     We started our journey on the belief that every single piece of authentic content, deserves attention from those who it was written for. You are not Seth Godin, but that does not mean your voice should not be heard. We want your content to reach out to people who are talking around it right now. 
  </p>   
  <p>
    We’re here to help people who write genuine content. Before we define what we mean by genuine content, let us describe what genuine content is not.
  </p>
  <p>Your content is not genuine if:
    <ol style="list-style-type:decimal;margin-left:20px;margin-top:-25px">
      <li>The sole purpose of your content is to get high traffic on your website.</li>
      <li>The content is stuffed with keywords for SEO purposes</li>
      <li>The sole purpose of your content is to get high traffic on your website.</li>
    </ol>  
  </p>
  <p>
    We define genuine content as the one that was written for truly helping your audience on what they are looking for. This is the true essence of Inbound Marketing.
  </p>
  <h3>How did it started?</h3>
  <p>
    As part of Inbound marketing for our company Idyllic Software, we produced truly authentic content. However we quickly realized that our content was not reaching those whom it was written for. Hence we wished goodbye to our Inbound Marketing tool with this <a href="http://blog.idyllic-software.com/why-did-i-quit-on-hubspot/">final word</a> and embarked on the journey to build C4C.


  </p>

  <h3>Team Behind C4C</h3>
  <ul>
    <li>Jinesh Parekh, CEO</li>
    <li>Amar Daxini, Engineering</li>
    <li>Sachin Gavas, User Experience</li>
    <li>Abhijit Rao, User Experience</li>
    <li>Vinod Sobale, Front End Developer</li>
  </ul>


</div> -->

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>C4C</title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <%= csrf_meta_tags %>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <link rel="stylesheet" href="http://weloveiconfonts.com/api/?family=fontawesome">
  <link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">
  <script type="text/javascript" src="//use.typekit.net/suy0tdp.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= stylesheet_link_tag :application, media: "all"%>
  <%= javascript_include_tag "application" %>
</head>
<body class='lp'>
  <div id="wrap">
    <section class='first-fold row'>
      <a href="/">
        <img src="/assets/dark-logo.png" alt="C4C Logo" />
      </a>
      <div class='blank-space-xlarge'></div>
      <h1>
        Yes, we think your content has only one mission,<br />
        <strong>Create Conversations!</strong>
      </h1>
      <div class='blank-space'></div>
      <p class="try-it">
        <a href="#mid-section">See how it works</a>, or try it once.
        <img src="/assets/arrow-down.png" alt="arrow down" />
      </p>
      <div class='blank-space'></div>
      <div class='row'>
        <div class='span8'>
          <div class='row'>
            <div class='row'>
              <div class='pull-left'>
                <strong>Import your blog</strong>
              </div>
              <div id='step-indicator' class='text-right'>
                Step 1 of 2
              </div>
            </div>
            <div class='import-blog-form row' data-step='1'>
              <%= form_tag signup_import_path do %>
                <%= text_field_tag :url , '', placeholder: 'http://yourblog.com/feed', id: 'top-url-input', class: 'user-input-feed-url span8', tabindex:'1' %>
                <input id='try-it-btn' type='button' value='try it' tabindex:'2' />
                <div id='feed-validating'><div></div></div>

                <button class="fontawesome-twitter btn btn-success" id="button-top-twitter-signup" name="submit" type="submit">
                  <span>Sign up</span>
                </button>
              <% end %>
            </div>
            <p>Tell us what you write about, and we'll help you find conversations around it.</p>
          </div>
        </div>
        <div class='span4 login text-center'>
          Already Using C4C?
          <%= link_to 'Log in', twitter_auth_path, class: 'btn btn-large btn-primary', tabindex: '3' %>
        </div>
      </div>
    </section>

    <div id="mid-out" class="row">
      <div id="mid-section">
        <h2>How it works?</h2>
        <div class="row demo-icon">
          <div class='span4'>
            <div class="information"></div>
            <p class="clearfix">You have brillion piece of information to share.</p>
          </div>
          <div class='span4'>
            <div class="thumbs-down"></div>
            <p class="clearfix">Since nobody knows it, no one comes to it.</p>
          </div>
          <div class='span4'>
            <div class="conversation"></div>
            <p class="clearfix">We'll take your content where people are talking about it.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <footer id="foot-contents">
    <img src="/assets/dark-logo.png" alt="C4C logo" class='logo' />
    <div class="foot-right">
      <div class="foot-rights">Copyrights © 2013 - C4C. All Rights Reserved</div>
      <div class="foot-text small-txt">
        <a href="/about_us">About.</a>
        <a href="/privacy-policy">Privacy.</a>
        <a href="/toc">Terms.</a>
      </div>
    </div>
  </footer>
  <script>
    jQuery( function( $ ) {
      VerifyFeed.init();

      // $( window ).scroll( function( eventData ) {
      //   console.log( $( 'body' ).scrollTop());
      // });
    });
  </script>
</body>

app/views/home/new_landing.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>C4C</title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <%= csrf_meta_tags %>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <link rel="stylesheet" href="http://weloveiconfonts.com/api/?family=fontawesome">
  <link rel="stylesheet" href="/assets/lib/onepage-scroll.css">
  <link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,200,800' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag :application, media: "all"%>
  <%= javascript_include_tag "application" %>
</head>
<body class='l-p'>
  <header>
    <a href="/"><img class="logo" src="/assets/dark-logo.png" alt="C4C Logo" /></a>
  </header>

  <section id="scroll-container">
    <article>
      <div class="slide first-fold">
        <div class="slide-inner">
          <h1>
            Yes, we think your content has only one mission,<br />
            <strong>Create Conversations!</strong>
          </h1>
          <p><a href="#">See how it works</a>, or try it once.</p>
        </div>
      </div>
    </article>

    <article>
      <div class="slide">
        <div class="slide-inner">
          <h2>Write.</h2>
          <p>You have a brilliant piece of information to share. Since nobody knows it, no one comes to it.</p>
          <a class="btn btn-primary next-slide" href="#">Next <i class="fontawesome-angle-down"></i></a>
        </div>
      </div>
    </article>

    <article>
      <div class="slide">
        <div class="slide-inner listen">
          <h2>Listen.</h2>
          <p>C4C fetches conversations relevant only to your blog content.</p>
          <a class="btn btn-primary next-slide" href="#">Next <i class="fontawesome-angle-down"></i></a>
        </div>
      </div>
    </article>

    <article>
      <div class="slide">
        <div class="slide-inner">
          <h2>Talk.</h2>
          <p>You participate in conversations happening around your content.</p>
          <a class="btn btn-primary next-slide" href="#">Next <i class="fontawesome-angle-down"></i></a>
        </div>
      </div>
    </article>

    <article>
      <div class="slide sign-up">
        <div class="slide-inner">
          <h2>Be Awesome.</h2>
          <p>Get on the list today.</p>
          <a href="#" class="btn btn-xlarge btn-warning">Sign Up with <i class="fontawesome-twitter"></i></a>
        </div>
      </div>
      <footer>
        <p class="pull-left">&copy; 2014. C4C by <a href="http://www.idyllic-software.com/" target="_blank">Idyllic Software</a>.</p>
        <ul class="pull-right">
          <li>
            <a href="#">About</a>
            <a href="#">Help/FAQ</a>
            <a href="#">Terms</a>
            <a href="#">Privacy</a>
            <a href="#">Contact</a>
            <a href="https://twitter.com/c4chq" target="_blank"><i class="fontawesome-twitter"></i></a>
          </li>
        </ul>
      </footer>
    </article>
  </section>

  <aside class="lp-screenshots"></aside>

  <script>
    jQuery( function( $ ) {
      $("#scroll-container").onepage_scroll({
        sectionContainer: "#scroll-container > article",
        loop: true,
        responsiveFallback: 600,
        afterMove: function( index ) {
          if ( $( 'body' ).width() < 1000 ) {  // Don't show this for narrow screens.
            return;
          }
          var currentSlideIndex = $( 'article.active' ).data( 'index' );
          switch ( currentSlideIndex ) {
            case 1:
              $( '.lp-screenshots' ).fadeOut().removeClass( 'scale1x');
              break;
            case 2:
              $( '.lp-screenshots' ).fadeIn().addClass( 'scale1x' );
              break;
            case 3:
              $( '.lp-screenshots' ).fadeIn().addClass( 'scale1x' );
              break;
            case 4:
              $( '.lp-screenshots' ).fadeIn().addClass( 'scale1x' );
              break;
            case 5:
              $( '.lp-screenshots' ).fadeOut().removeClass( 'scale1x');
              break;
            default:
              console.log( 'something went unexpected.' );
          }
        }
      });
      $( '.next-slide' ).click( function( event ) {
        event.preventDefault();
        $( '#scroll-container' ).moveDown();
      });
      VerifyFeed.init();
    });
  </script>
</body>
</html>

app/views/home/old_landing.html.erb
<head>
  <%= stylesheet_link_tag :application, media: "all"%>
  <%= javascript_include_tag "application" %>
  <title>C4C</title>
  <meta charset="UTF-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <link rel="stylesheet" href="http://weloveiconfonts.com/api/?family=fontawesome">
  <link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrap">
  <div class="up-sec">
    <div id="up-section">
      <div id="logo-signin">
        <div class="logo-container logo-center">
        <a href="/">
            <img src="/assets/dark-logo.png" alt="" width="105px" height="55px" border="0" />
        </a>
        </div>
        <div id="rightsec">
          <%= form_tag signup_import_path do %>
            <div class="enter-blog-url">
              <%= text_field_tag :url , '', placeholder: 'http://yourblog.com/feed', id: 'top-url-input', class: 'user-input-feed-url' %>
              <button class="fontawesome-twitter" id="button-top-twitter-signup" name="submit" type="submit">
                <span>
                  <%= 'Sign Up with Twitter' %>
                </span>
              </button>
            </div>
          <% end %>
        </div>
      </div>
      <h2>
        Your content has only one mission
        <div>Create Conversations!</div>
      </h2>
      <div class="try-it"></div>
      <%= form_tag signup_import_path do %>
      <div class="import-note">Import your blog</div>
        <%= text_field_tag :url, '', placeholder: 'http://yourblog.com/feed', class: 'user-input-feed-url main', tabindex: '1' %>
        <div class="import-feed">
          <button class="fontawesome-twitter" id="button-main-twitter-signup" name="submit" type="submit" value="'Sign up using Twitter'">
            Sign up using Twitter
          </button>
          <div class="registered-user">
            <span>
              <%= 'Already have an account ?' %>
            </span>
            <%= link_to 'Log in with Twitter', twitter_auth_path %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div id="mid-out">
    <div id="mid-section">
      <h1>How it works ?</h1>
      <div class="demo-icon">
        <div>
          <div class="information"></div>
          <p class="clearfix">You have brillion piece of information to share.</p>
        </div>
        <div>
          <div class="thumbs-down"></div>
          <p class="clearfix">Since nobody knows it, no one comes to it.</p>
        </div>
        <div>
          <div class="conversation"></div>
          <p class="clearfix">
  "We'll take your content where people are talking about it."
</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="foot-contents">
  <img src="/assets/dark-logo.png" alt="C4C logo" />
  <div class="foot-right">
  <div class="foot-rights">Copyrights © 2013 - C4C. All Rights Reserved</div>
    <div class="foot-text">
      <a href="#">About.</a>
      <a href="#">Privacy.</a>
      <a href="#">Terms.</a>
    </div>
  </div>
</div>
  <script>
    VerifyFeed.init();
  </script>
</body>

app/views/home/privacy_policy.html.erb
<div class="privacy-policy-page">
    <h2>C4C Privacy Policies</h2>
    <span>1. ACCEPTANCE OF TERMS</span>
    <p>1.1 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, magni, sequi aperiam voluptatibus labore rem facere sunt quae? Voluptatibus, porro, recusandae blanditiis praesentium aspernatur facere modi consequatur rerum aperiam tempora.</p>
    <p>1.2 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, magni, sequi aperiam voluptatibus labore rem facere sunt quae? Voluptatibus, porro, recusandae blanditiis praesentium aspernatur facere modi consequatur rerum aperiam tempora.</p>
    <span>2.ENVOY SERVICES</span>
    <p>2.1 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, magni, sequi aperiam voluptatibus labore rem facere sunt quae? Voluptatibus, porro, recusandae blanditiis praesentium aspernatur facere modi consequatur rerum aperiam tempora.</p>
    <h4>Contact Information</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, magni, sequi aperiam voluptatibus labore rem facere sunt quae? Voluptatibus, porro, recusandae blanditiis praesentium aspernatur facere modi consequatur rerum aperiam tempora.</p>
    <address>
        <strong>Idyllic Software</strong>
        <span>212 Clara st.</span>
        <span>San Fransisco, CA 912121</span>
        <a href="mailto:feedback@c4chq.com">Contact Us</a>
    </address>
</div>

app/views/home/toc.html.erb
<div class="toc-page">
    <div class="last-update">
        <div class="disabled-link"> Last update on :</div>
        <span> 7 Jan 2014</span>
    </div>
    <h2>C4C Service Agreement</h2>
    <span>1. ACCEPTANCE OF TERMS</span>
    <p>1.1 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, magni, sequi aperiam voluptatibus labore rem facere sunt quae? Voluptatibus, porro, recusandae blanditiis praesentium aspernatur facere modi consequatur rerum aperiam tempora.</p>
    <p>1.2 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, magni, sequi aperiam voluptatibus labore rem facere sunt quae? Voluptatibus, porro, recusandae blanditiis praesentium aspernatur facere modi consequatur rerum aperiam tempora.</p>
    <span>2. ENVOY SERVICES</span>
    <p>2.1 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, magni, sequi aperiam voluptatibus labore rem facere sunt quae? Voluptatibus, porro, recusandae blanditiis praesentium aspernatur facere modi consequatur rerum aperiam tempora.</p>
    <h4>Contact Information</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo, magni, sequi aperiam voluptatibus labore rem facere sunt quae? Voluptatibus, porro, recusandae blanditiis praesentium aspernatur facere modi consequatur rerum aperiam tempora.</p>
    <address>
        <strong>Idyllic Software</strong>
        <span>212 Clara st.</span>
        <span>San Fransisco, CA 912121</span>
        <a href="mailto:feedback@c4chq.com">Contact Us</a>
    </address>
</div>